# Generated by Django 2.2.4 on 2019-08-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=300)),
                ('post_body', models.TextField(blank=True, null=True)),
                ('post_author', models.CharField(max_length=30)),
                ('post_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
